<?php
/**
 * CatalogoClavesPrevencion
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reporte de Crédito Consolidado Personas Morales
 *
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RCCPMV2\Simulacion\MX\Client\Model;
use \RCCPMV2\Simulacion\MX\Client\ObjectSerializer;

/**
 * CatalogoClavesPrevencion Class Doc Comment
 *
 * @category Class
 * @description &lt;table&gt; &lt;thead&gt; &lt;tr&gt; &lt;th&gt;Clave&lt;/th&gt; &lt;th&gt;Descripción&lt;/th&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;tr&gt; &lt;td&gt;78&lt;/td&gt; &lt;td&gt;Negocio receptor de tarjetas de crédito que ocasionó pérdida al Usuario&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;79&lt;/td&gt; &lt;td&gt;Persona relacionada con la empresa o con Persona Física con Actividad Empresarial con clave de prevención&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;80&lt;/td&gt; &lt;td&gt;Cliente declarado en quiebra, suspensión de pagos o en concurso mercantil&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;81&lt;/td&gt; &lt;td&gt;Cliente en trámite judicial&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;82&lt;/td&gt; &lt;td&gt;Cliente que propició pérdida al Otorgante por fraude comprobado, declarado conforme a sentencia judicial&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;83&lt;/td&gt; &lt;td&gt;Cliente que solicitó y/o acordó con el Otorgante liquidación del crédito con pago menor a la deuda total&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;84&lt;/td&gt; &lt;td&gt;El usuario no ha podido localizar al Cliente, titular de la cuenta&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;85&lt;/td&gt; &lt;td&gt;Cliente desvió recursos a fines distintos a los pactados, debidamente comprobado&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;86&lt;/td&gt; &lt;td&gt;Cliente que dispuso de las garantías que respaldan el crédito sin autorización del Otorgante&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;87&lt;/td&gt; &lt;td&gt;Cliente que enajena o cambia régimen de propiedad de sus bienes o permite gravámenes sobre los mismos&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;88&lt;/td&gt; &lt;td&gt;Cliente que dispuso de las retenciones de sus trabajadores, no enterando a la Institución correspondiente&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;92&lt;/td&gt; &lt;td&gt;Cliente que propició pérdida total al Otorgante&lt;/td&gt; &lt;/tr&gt; &lt;/table&gt;
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CatalogoClavesPrevencion
{
    /**
     * Possible values of this enum
     */
    const _78 = '78';
    const _79 = '79';
    const _80 = '80';
    const _81 = '81';
    const _82 = '82';
    const _83 = '83';
    const _84 = '84';
    const _85 = '85';
    const _86 = '86';
    const _87 = '87';
    const _88 = '88';
    const _92 = '92';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_78,
            self::_79,
            self::_80,
            self::_81,
            self::_82,
            self::_83,
            self::_84,
            self::_85,
            self::_86,
            self::_87,
            self::_88,
            self::_92
        ];
    }
}
