<?php
/**
 * Comerciales
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reporte de Crédito Consolidado Personas Morales
 *
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RCCPMV2\Simulacion\MX\Client\Model;

use \ArrayAccess;
use \RCCPMV2\Simulacion\MX\Client\ObjectSerializer;

/**
 * Comerciales Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Comerciales implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'comerciales';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ultimos3meses' => 'int',
        'ultimos12meses' => 'int',
        'ultimos24meses' => 'int',
        'mas24meses' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ultimos3meses' => null,
        'ultimos12meses' => null,
        'ultimos24meses' => null,
        'mas24meses' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ultimos3meses' => 'ultimos3meses',
        'ultimos12meses' => 'ultimos12meses',
        'ultimos24meses' => 'ultimos24meses',
        'mas24meses' => 'mas24meses'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ultimos3meses' => 'setUltimos3meses',
        'ultimos12meses' => 'setUltimos12meses',
        'ultimos24meses' => 'setUltimos24meses',
        'mas24meses' => 'setMas24meses'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ultimos3meses' => 'getUltimos3meses',
        'ultimos12meses' => 'getUltimos12meses',
        'ultimos24meses' => 'getUltimos24meses',
        'mas24meses' => 'getMas24meses'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ultimos3meses'] = isset($data['ultimos3meses']) ? $data['ultimos3meses'] : null;
        $this->container['ultimos12meses'] = isset($data['ultimos12meses']) ? $data['ultimos12meses'] : null;
        $this->container['ultimos24meses'] = isset($data['ultimos24meses']) ? $data['ultimos24meses'] : null;
        $this->container['mas24meses'] = isset($data['mas24meses']) ? $data['mas24meses'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ultimos3meses
     *
     * @return int
     */
    public function getUltimos3meses()
    {
        return $this->container['ultimos3meses'];
    }

    /**
     * Sets ultimos3meses
     *
     * @param int $ultimos3meses Consultas en los último 3 meses.
     *
     * @return $this
     */
    public function setUltimos3meses($ultimos3meses)
    {
        $this->container['ultimos3meses'] = $ultimos3meses;

        return $this;
    }

    /**
     * Gets ultimos12meses
     *
     * @return int
     */
    public function getUltimos12meses()
    {
        return $this->container['ultimos12meses'];
    }

    /**
     * Sets ultimos12meses
     *
     * @param int $ultimos12meses Consultas en los últimos 12 meses.
     *
     * @return $this
     */
    public function setUltimos12meses($ultimos12meses)
    {
        $this->container['ultimos12meses'] = $ultimos12meses;

        return $this;
    }

    /**
     * Gets ultimos24meses
     *
     * @return int
     */
    public function getUltimos24meses()
    {
        return $this->container['ultimos24meses'];
    }

    /**
     * Sets ultimos24meses
     *
     * @param int $ultimos24meses Consultas en los últimos 24 meses.
     *
     * @return $this
     */
    public function setUltimos24meses($ultimos24meses)
    {
        $this->container['ultimos24meses'] = $ultimos24meses;

        return $this;
    }

    /**
     * Gets mas24meses
     *
     * @return int
     */
    public function getMas24meses()
    {
        return $this->container['mas24meses'];
    }

    /**
     * Sets mas24meses
     *
     * @param int $mas24meses Consultas en más de 24 meses.
     *
     * @return $this
     */
    public function setMas24meses($mas24meses)
    {
        $this->container['mas24meses'] = $mas24meses;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
