<?php
/**
 * CreditoPMInner
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reporte de Crédito Consolidado Personas Morales
 *
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RCCPMV2\Simulacion\MX\Client\Model;

use \ArrayAccess;
use \RCCPMV2\Simulacion\MX\Client\ObjectSerializer;

/**
 * CreditoPMInner Class Doc Comment
 *
 * @category Class
 * @description El elemento de crédito contiene el comportamiento actual e histórico del crédito del consumidor, este elemento se repite dependiendo del número de cuentas del consumidor.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreditoPMInner implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'creditoPM_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'rfc' => 'string',
        'nombre_otorgante' => 'string',
        'tipo_contrato' => 'int',
        'num_cuenta' => 'string',
        'periodo_act' => 'string',
        'cve_tipo_negocio' => '\RCCPMV2\Simulacion\MX\Client\Model\CatalogoTipoNegocio',
        'desc_tipo_negocio' => 'string',
        'saldo_inicial' => 'int',
        'cve_moneda' => '\RCCPMV2\Simulacion\MX\Client\Model\CatalogoMoneda',
        'plazo' => 'int',
        'claves_observacion' => '\RCCPMV2\Simulacion\MX\Client\Model\CatalogoClavesObservacion',
        'fecha_apertura' => 'string',
        'can_pago_efectivo' => 'int',
        'can_quita' => 'int',
        'can_duracion_pago' => 'int',
        'can_quebranto_castigo' => 'int',
        'historico_pago' => 'string',
        'registro_impugnado' => 'string',
        'saldo_total' => 'int',
        'vigente' => 'int',
        'saldo_vencido' => 'int',
        'saldo_vencido29dias' => 'int',
        'saldo_vencido59dias' => 'float',
        'saldo_vencido89dias' => 'int',
        'saldo_vencido119dias' => 'float',
        'saldo_vencido179dias' => 'int',
        'saldo_vencido180_mas_dias' => 'int',
        'atraso_mayor' => 'int',
        'origen' => 'string',
        'estatus_credito' => 'string',
        'desc_tipo_contrato' => '\RCCPMV2\Simulacion\MX\Client\Model\CatalogoTipoContrato'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'rfc' => null,
        'nombre_otorgante' => null,
        'tipo_contrato' => null,
        'num_cuenta' => null,
        'periodo_act' => 'yyyy-MM',
        'cve_tipo_negocio' => null,
        'desc_tipo_negocio' => null,
        'saldo_inicial' => null,
        'cve_moneda' => null,
        'plazo' => null,
        'claves_observacion' => null,
        'fecha_apertura' => 'yyyy-MM-dd',
        'can_pago_efectivo' => null,
        'can_quita' => null,
        'can_duracion_pago' => null,
        'can_quebranto_castigo' => null,
        'historico_pago' => null,
        'registro_impugnado' => null,
        'saldo_total' => null,
        'vigente' => null,
        'saldo_vencido' => null,
        'saldo_vencido29dias' => 'int32',
        'saldo_vencido59dias' => 'float',
        'saldo_vencido89dias' => 'int32',
        'saldo_vencido119dias' => 'float',
        'saldo_vencido179dias' => 'int32',
        'saldo_vencido180_mas_dias' => 'int32',
        'atraso_mayor' => null,
        'origen' => null,
        'estatus_credito' => null,
        'desc_tipo_contrato' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rfc' => 'RFC',
        'nombre_otorgante' => 'nombreOtorgante',
        'tipo_contrato' => 'tipoContrato',
        'num_cuenta' => 'numCuenta',
        'periodo_act' => 'periodoAct',
        'cve_tipo_negocio' => 'cveTipoNegocio',
        'desc_tipo_negocio' => 'DescTipoNegocio',
        'saldo_inicial' => 'saldoInicial',
        'cve_moneda' => 'cveMoneda',
        'plazo' => 'plazo',
        'claves_observacion' => 'clavesObservacion',
        'fecha_apertura' => 'fechaApertura',
        'can_pago_efectivo' => 'CanPagoEfectivo',
        'can_quita' => 'CanQuita',
        'can_duracion_pago' => 'CanDuracionPago',
        'can_quebranto_castigo' => 'CanQuebrantoCastigo',
        'historico_pago' => 'historicoPago',
        'registro_impugnado' => 'registroImpugnado',
        'saldo_total' => 'saldoTotal',
        'vigente' => 'vigente',
        'saldo_vencido' => 'saldoVencido',
        'saldo_vencido29dias' => 'saldoVencido29dias',
        'saldo_vencido59dias' => 'saldoVencido59dias',
        'saldo_vencido89dias' => 'saldoVencido89dias',
        'saldo_vencido119dias' => 'saldoVencido119dias',
        'saldo_vencido179dias' => 'saldoVencido179dias',
        'saldo_vencido180_mas_dias' => 'saldoVencido180MasDias',
        'atraso_mayor' => 'atrasoMayor',
        'origen' => 'origen',
        'estatus_credito' => 'estatusCredito',
        'desc_tipo_contrato' => 'DescTipoContrato'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rfc' => 'setRfc',
        'nombre_otorgante' => 'setNombreOtorgante',
        'tipo_contrato' => 'setTipoContrato',
        'num_cuenta' => 'setNumCuenta',
        'periodo_act' => 'setPeriodoAct',
        'cve_tipo_negocio' => 'setCveTipoNegocio',
        'desc_tipo_negocio' => 'setDescTipoNegocio',
        'saldo_inicial' => 'setSaldoInicial',
        'cve_moneda' => 'setCveMoneda',
        'plazo' => 'setPlazo',
        'claves_observacion' => 'setClavesObservacion',
        'fecha_apertura' => 'setFechaApertura',
        'can_pago_efectivo' => 'setCanPagoEfectivo',
        'can_quita' => 'setCanQuita',
        'can_duracion_pago' => 'setCanDuracionPago',
        'can_quebranto_castigo' => 'setCanQuebrantoCastigo',
        'historico_pago' => 'setHistoricoPago',
        'registro_impugnado' => 'setRegistroImpugnado',
        'saldo_total' => 'setSaldoTotal',
        'vigente' => 'setVigente',
        'saldo_vencido' => 'setSaldoVencido',
        'saldo_vencido29dias' => 'setSaldoVencido29dias',
        'saldo_vencido59dias' => 'setSaldoVencido59dias',
        'saldo_vencido89dias' => 'setSaldoVencido89dias',
        'saldo_vencido119dias' => 'setSaldoVencido119dias',
        'saldo_vencido179dias' => 'setSaldoVencido179dias',
        'saldo_vencido180_mas_dias' => 'setSaldoVencido180MasDias',
        'atraso_mayor' => 'setAtrasoMayor',
        'origen' => 'setOrigen',
        'estatus_credito' => 'setEstatusCredito',
        'desc_tipo_contrato' => 'setDescTipoContrato'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rfc' => 'getRfc',
        'nombre_otorgante' => 'getNombreOtorgante',
        'tipo_contrato' => 'getTipoContrato',
        'num_cuenta' => 'getNumCuenta',
        'periodo_act' => 'getPeriodoAct',
        'cve_tipo_negocio' => 'getCveTipoNegocio',
        'desc_tipo_negocio' => 'getDescTipoNegocio',
        'saldo_inicial' => 'getSaldoInicial',
        'cve_moneda' => 'getCveMoneda',
        'plazo' => 'getPlazo',
        'claves_observacion' => 'getClavesObservacion',
        'fecha_apertura' => 'getFechaApertura',
        'can_pago_efectivo' => 'getCanPagoEfectivo',
        'can_quita' => 'getCanQuita',
        'can_duracion_pago' => 'getCanDuracionPago',
        'can_quebranto_castigo' => 'getCanQuebrantoCastigo',
        'historico_pago' => 'getHistoricoPago',
        'registro_impugnado' => 'getRegistroImpugnado',
        'saldo_total' => 'getSaldoTotal',
        'vigente' => 'getVigente',
        'saldo_vencido' => 'getSaldoVencido',
        'saldo_vencido29dias' => 'getSaldoVencido29dias',
        'saldo_vencido59dias' => 'getSaldoVencido59dias',
        'saldo_vencido89dias' => 'getSaldoVencido89dias',
        'saldo_vencido119dias' => 'getSaldoVencido119dias',
        'saldo_vencido179dias' => 'getSaldoVencido179dias',
        'saldo_vencido180_mas_dias' => 'getSaldoVencido180MasDias',
        'atraso_mayor' => 'getAtrasoMayor',
        'origen' => 'getOrigen',
        'estatus_credito' => 'getEstatusCredito',
        'desc_tipo_contrato' => 'getDescTipoContrato'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rfc'] = isset($data['rfc']) ? $data['rfc'] : null;
        $this->container['nombre_otorgante'] = isset($data['nombre_otorgante']) ? $data['nombre_otorgante'] : null;
        $this->container['tipo_contrato'] = isset($data['tipo_contrato']) ? $data['tipo_contrato'] : null;
        $this->container['num_cuenta'] = isset($data['num_cuenta']) ? $data['num_cuenta'] : null;
        $this->container['periodo_act'] = isset($data['periodo_act']) ? $data['periodo_act'] : null;
        $this->container['cve_tipo_negocio'] = isset($data['cve_tipo_negocio']) ? $data['cve_tipo_negocio'] : null;
        $this->container['desc_tipo_negocio'] = isset($data['desc_tipo_negocio']) ? $data['desc_tipo_negocio'] : null;
        $this->container['saldo_inicial'] = isset($data['saldo_inicial']) ? $data['saldo_inicial'] : null;
        $this->container['cve_moneda'] = isset($data['cve_moneda']) ? $data['cve_moneda'] : null;
        $this->container['plazo'] = isset($data['plazo']) ? $data['plazo'] : null;
        $this->container['claves_observacion'] = isset($data['claves_observacion']) ? $data['claves_observacion'] : null;
        $this->container['fecha_apertura'] = isset($data['fecha_apertura']) ? $data['fecha_apertura'] : null;
        $this->container['can_pago_efectivo'] = isset($data['can_pago_efectivo']) ? $data['can_pago_efectivo'] : null;
        $this->container['can_quita'] = isset($data['can_quita']) ? $data['can_quita'] : null;
        $this->container['can_duracion_pago'] = isset($data['can_duracion_pago']) ? $data['can_duracion_pago'] : null;
        $this->container['can_quebranto_castigo'] = isset($data['can_quebranto_castigo']) ? $data['can_quebranto_castigo'] : null;
        $this->container['historico_pago'] = isset($data['historico_pago']) ? $data['historico_pago'] : null;
        $this->container['registro_impugnado'] = isset($data['registro_impugnado']) ? $data['registro_impugnado'] : null;
        $this->container['saldo_total'] = isset($data['saldo_total']) ? $data['saldo_total'] : null;
        $this->container['vigente'] = isset($data['vigente']) ? $data['vigente'] : null;
        $this->container['saldo_vencido'] = isset($data['saldo_vencido']) ? $data['saldo_vencido'] : null;
        $this->container['saldo_vencido29dias'] = isset($data['saldo_vencido29dias']) ? $data['saldo_vencido29dias'] : null;
        $this->container['saldo_vencido59dias'] = isset($data['saldo_vencido59dias']) ? $data['saldo_vencido59dias'] : null;
        $this->container['saldo_vencido89dias'] = isset($data['saldo_vencido89dias']) ? $data['saldo_vencido89dias'] : null;
        $this->container['saldo_vencido119dias'] = isset($data['saldo_vencido119dias']) ? $data['saldo_vencido119dias'] : null;
        $this->container['saldo_vencido179dias'] = isset($data['saldo_vencido179dias']) ? $data['saldo_vencido179dias'] : null;
        $this->container['saldo_vencido180_mas_dias'] = isset($data['saldo_vencido180_mas_dias']) ? $data['saldo_vencido180_mas_dias'] : null;
        $this->container['atraso_mayor'] = isset($data['atraso_mayor']) ? $data['atraso_mayor'] : null;
        $this->container['origen'] = isset($data['origen']) ? $data['origen'] : null;
        $this->container['estatus_credito'] = isset($data['estatus_credito']) ? $data['estatus_credito'] : null;
        $this->container['desc_tipo_contrato'] = isset($data['desc_tipo_contrato']) ? $data['desc_tipo_contrato'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rfc
     *
     * @return string
     */
    public function getRfc()
    {
        return $this->container['rfc'];
    }

    /**
     * Sets rfc
     *
     * @param string $rfc rfc
     *
     * @return $this
     */
    public function setRfc($rfc)
    {
        $this->container['rfc'] = $rfc;

        return $this;
    }

    /**
     * Gets nombre_otorgante
     *
     * @return string
     */
    public function getNombreOtorgante()
    {
        return $this->container['nombre_otorgante'];
    }

    /**
     * Sets nombre_otorgante
     *
     * @param string $nombre_otorgante Contiene el Nombre del Otorgante de Crédito que reporto el Crédito. Ver Tabla: Tipo de Negocio. <br>Nota: Este elemento solo es reportado para reporte de crédito especial.
     *
     * @return $this
     */
    public function setNombreOtorgante($nombre_otorgante)
    {
        $this->container['nombre_otorgante'] = $nombre_otorgante;

        return $this;
    }

    /**
     * Gets tipo_contrato
     *
     * @return int
     */
    public function getTipoContrato()
    {
        return $this->container['tipo_contrato'];
    }

    /**
     * Sets tipo_contrato
     *
     * @param int $tipo_contrato Número de contrato.
     *
     * @return $this
     */
    public function setTipoContrato($tipo_contrato)
    {
        $this->container['tipo_contrato'] = $tipo_contrato;

        return $this;
    }

    /**
     * Gets num_cuenta
     *
     * @return string
     */
    public function getNumCuenta()
    {
        return $this->container['num_cuenta'];
    }

    /**
     * Sets num_cuenta
     *
     * @param string $num_cuenta Número de cuenta.
     *
     * @return $this
     */
    public function setNumCuenta($num_cuenta)
    {
        $this->container['num_cuenta'] = $num_cuenta;

        return $this;
    }

    /**
     * Gets periodo_act
     *
     * @return string
     */
    public function getPeriodoAct()
    {
        return $this->container['periodo_act'];
    }

    /**
     * Sets periodo_act
     *
     * @param string $periodo_act Fecha de periodo actual, en el formato especificado (por defecto yyyy-MM).
     *
     * @return $this
     */
    public function setPeriodoAct($periodo_act)
    {
        $this->container['periodo_act'] = $periodo_act;

        return $this;
    }

    /**
     * Gets cve_tipo_negocio
     *
     * @return \Swagger\Client\Model\CatalogoTipoNegocio
     */
    public function getCveTipoNegocio()
    {
        return $this->container['cve_tipo_negocio'];
    }

    /**
     * Sets cve_tipo_negocio
     *
     * @param \Swagger\Client\Model\CatalogoTipoNegocio $cve_tipo_negocio cve_tipo_negocio
     *
     * @return $this
     */
    public function setCveTipoNegocio($cve_tipo_negocio)
    {
        $this->container['cve_tipo_negocio'] = $cve_tipo_negocio;

        return $this;
    }

    /**
     * Gets desc_tipo_negocio
     *
     * @return string
     */
    public function getDescTipoNegocio()
    {
        return $this->container['desc_tipo_negocio'];
    }

    /**
     * Sets desc_tipo_negocio
     *
     * @param string $desc_tipo_negocio desc_tipo_negocio
     *
     * @return $this
     */
    public function setDescTipoNegocio($desc_tipo_negocio)
    {
        $this->container['desc_tipo_negocio'] = $desc_tipo_negocio;

        return $this;
    }

    /**
     * Gets saldo_inicial
     *
     * @return int
     */
    public function getSaldoInicial()
    {
        return $this->container['saldo_inicial'];
    }

    /**
     * Sets saldo_inicial
     *
     * @param int $saldo_inicial Saldo inicial del crédito.
     *
     * @return $this
     */
    public function setSaldoInicial($saldo_inicial)
    {
        $this->container['saldo_inicial'] = $saldo_inicial;

        return $this;
    }

    /**
     * Gets cve_moneda
     *
     * @return \Swagger\Client\Model\CatalogoMoneda
     */
    public function getCveMoneda()
    {
        return $this->container['cve_moneda'];
    }

    /**
     * Sets cve_moneda
     *
     * @param \Swagger\Client\Model\CatalogoMoneda $cve_moneda cve_moneda
     *
     * @return $this
     */
    public function setCveMoneda($cve_moneda)
    {
        $this->container['cve_moneda'] = $cve_moneda;

        return $this;
    }

    /**
     * Gets plazo
     *
     * @return int
     */
    public function getPlazo()
    {
        return $this->container['plazo'];
    }

    /**
     * Sets plazo
     *
     * @param int $plazo Término en el que se pactó el crédito. Deberá reportarse en días.
     *
     * @return $this
     */
    public function setPlazo($plazo)
    {
        $this->container['plazo'] = $plazo;

        return $this;
    }

    /**
     * Gets claves_observacion
     *
     * @return \Swagger\Client\Model\CatalogoClavesObservacion
     */
    public function getClavesObservacion()
    {
        return $this->container['claves_observacion'];
    }

    /**
     * Sets claves_observacion
     *
     * @param \Swagger\Client\Model\CatalogoClavesObservacion $claves_observacion claves_observacion
     *
     * @return $this
     */
    public function setClavesObservacion($claves_observacion)
    {
        $this->container['claves_observacion'] = $claves_observacion;

        return $this;
    }

    /**
     * Gets fecha_apertura
     *
     * @return string
     */
    public function getFechaApertura()
    {
        return $this->container['fecha_apertura'];
    }

    /**
     * Sets fecha_apertura
     *
     * @param string $fecha_apertura Fecha de apertura del crédito, en el formato especificado (por defecto yyyy-MM-dd).
     *
     * @return $this
     */
    public function setFechaApertura($fecha_apertura)
    {
        $this->container['fecha_apertura'] = $fecha_apertura;

        return $this;
    }

    /**
     * Gets can_pago_efectivo
     *
     * @return int
     */
    public function getCanPagoEfectivo()
    {
        return $this->container['can_pago_efectivo'];
    }

    /**
     * Sets can_pago_efectivo
     *
     * @param int $can_pago_efectivo can_pago_efectivo
     *
     * @return $this
     */
    public function setCanPagoEfectivo($can_pago_efectivo)
    {
        $this->container['can_pago_efectivo'] = $can_pago_efectivo;

        return $this;
    }

    /**
     * Gets can_quita
     *
     * @return int
     */
    public function getCanQuita()
    {
        return $this->container['can_quita'];
    }

    /**
     * Sets can_quita
     *
     * @param int $can_quita can_quita
     *
     * @return $this
     */
    public function setCanQuita($can_quita)
    {
        $this->container['can_quita'] = $can_quita;

        return $this;
    }

    /**
     * Gets can_duracion_pago
     *
     * @return int
     */
    public function getCanDuracionPago()
    {
        return $this->container['can_duracion_pago'];
    }

    /**
     * Sets can_duracion_pago
     *
     * @param int $can_duracion_pago can_duracion_pago
     *
     * @return $this
     */
    public function setCanDuracionPago($can_duracion_pago)
    {
        $this->container['can_duracion_pago'] = $can_duracion_pago;

        return $this;
    }

    /**
     * Gets can_quebranto_castigo
     *
     * @return int
     */
    public function getCanQuebrantoCastigo()
    {
        return $this->container['can_quebranto_castigo'];
    }

    /**
     * Sets can_quebranto_castigo
     *
     * @param int $can_quebranto_castigo can_quebranto_castigo
     *
     * @return $this
     */
    public function setCanQuebrantoCastigo($can_quebranto_castigo)
    {
        $this->container['can_quebranto_castigo'] = $can_quebranto_castigo;

        return $this;
    }

    /**
     * Gets historico_pago
     *
     * @return string
     */
    public function getHistoricoPago()
    {
        return $this->container['historico_pago'];
    }

    /**
     * Sets historico_pago
     *
     * @param string $historico_pago Patrón histórico de pagos
     *
     * @return $this
     */
    public function setHistoricoPago($historico_pago)
    {
        $this->container['historico_pago'] = $historico_pago;

        return $this;
    }

    /**
     * Gets registro_impugnado
     *
     * @return string
     */
    public function getRegistroImpugnado()
    {
        return $this->container['registro_impugnado'];
    }

    /**
     * Sets registro_impugnado
     *
     * @param string $registro_impugnado Si contiene RI, el registro está impugnado.
     *
     * @return $this
     */
    public function setRegistroImpugnado($registro_impugnado)
    {
        $this->container['registro_impugnado'] = $registro_impugnado;

        return $this;
    }

    /**
     * Gets saldo_total
     *
     * @return int
     */
    public function getSaldoTotal()
    {
        return $this->container['saldo_total'];
    }

    /**
     * Sets saldo_total
     *
     * @param int $saldo_total Saldo total del crédito.
     *
     * @return $this
     */
    public function setSaldoTotal($saldo_total)
    {
        $this->container['saldo_total'] = $saldo_total;

        return $this;
    }

    /**
     * Gets vigente
     *
     * @return int
     */
    public function getVigente()
    {
        return $this->container['vigente'];
    }

    /**
     * Sets vigente
     *
     * @param int $vigente Monto Vigente. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setVigente($vigente)
    {
        $this->container['vigente'] = $vigente;

        return $this;
    }

    /**
     * Gets saldo_vencido
     *
     * @return int
     */
    public function getSaldoVencido()
    {
        return $this->container['saldo_vencido'];
    }

    /**
     * Sets saldo_vencido
     *
     * @param int $saldo_vencido saldo_vencido
     *
     * @return $this
     */
    public function setSaldoVencido($saldo_vencido)
    {
        $this->container['saldo_vencido'] = $saldo_vencido;

        return $this;
    }

    /**
     * Gets saldo_vencido29dias
     *
     * @return int
     */
    public function getSaldoVencido29dias()
    {
        return $this->container['saldo_vencido29dias'];
    }

    /**
     * Sets saldo_vencido29dias
     *
     * @param int $saldo_vencido29dias Vencido de 1 a 29 días. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setSaldoVencido29dias($saldo_vencido29dias)
    {
        $this->container['saldo_vencido29dias'] = $saldo_vencido29dias;

        return $this;
    }

    /**
     * Gets saldo_vencido59dias
     *
     * @return float
     */
    public function getSaldoVencido59dias()
    {
        return $this->container['saldo_vencido59dias'];
    }

    /**
     * Sets saldo_vencido59dias
     *
     * @param float $saldo_vencido59dias Vencido de 30 a 59 días. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setSaldoVencido59dias($saldo_vencido59dias)
    {
        $this->container['saldo_vencido59dias'] = $saldo_vencido59dias;

        return $this;
    }

    /**
     * Gets saldo_vencido89dias
     *
     * @return int
     */
    public function getSaldoVencido89dias()
    {
        return $this->container['saldo_vencido89dias'];
    }

    /**
     * Sets saldo_vencido89dias
     *
     * @param int $saldo_vencido89dias Vencido de 60 a 89 días. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setSaldoVencido89dias($saldo_vencido89dias)
    {
        $this->container['saldo_vencido89dias'] = $saldo_vencido89dias;

        return $this;
    }

    /**
     * Gets saldo_vencido119dias
     *
     * @return float
     */
    public function getSaldoVencido119dias()
    {
        return $this->container['saldo_vencido119dias'];
    }

    /**
     * Sets saldo_vencido119dias
     *
     * @param float $saldo_vencido119dias Vencido de 90 a 119 días. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setSaldoVencido119dias($saldo_vencido119dias)
    {
        $this->container['saldo_vencido119dias'] = $saldo_vencido119dias;

        return $this;
    }

    /**
     * Gets saldo_vencido179dias
     *
     * @return int
     */
    public function getSaldoVencido179dias()
    {
        return $this->container['saldo_vencido179dias'];
    }

    /**
     * Sets saldo_vencido179dias
     *
     * @param int $saldo_vencido179dias Vencido de 120 a 179 días. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setSaldoVencido179dias($saldo_vencido179dias)
    {
        $this->container['saldo_vencido179dias'] = $saldo_vencido179dias;

        return $this;
    }

    /**
     * Gets saldo_vencido180_mas_dias
     *
     * @return int
     */
    public function getSaldoVencido180MasDias()
    {
        return $this->container['saldo_vencido180_mas_dias'];
    }

    /**
     * Sets saldo_vencido180_mas_dias
     *
     * @param int $saldo_vencido180_mas_dias Vencido 180 días a más. Sólo con créditos abiertos.
     *
     * @return $this
     */
    public function setSaldoVencido180MasDias($saldo_vencido180_mas_dias)
    {
        $this->container['saldo_vencido180_mas_dias'] = $saldo_vencido180_mas_dias;

        return $this;
    }

    /**
     * Gets atraso_mayor
     *
     * @return int
     */
    public function getAtrasoMayor()
    {
        return $this->container['atraso_mayor'];
    }

    /**
     * Sets atraso_mayor
     *
     * @param int $atraso_mayor Muestra la cantidad exacta de días de atraso cuando se reportan montos con vencimiento.
     *
     * @return $this
     */
    public function setAtrasoMayor($atraso_mayor)
    {
        $this->container['atraso_mayor'] = $atraso_mayor;

        return $this;
    }

    /**
     * Gets origen
     *
     * @return string
     */
    public function getOrigen()
    {
        return $this->container['origen'];
    }

    /**
     * Sets origen
     *
     * @param string $origen origen
     *
     * @return $this
     */
    public function setOrigen($origen)
    {
        $this->container['origen'] = $origen;

        return $this;
    }

    /**
     * Gets estatus_credito
     *
     * @return string
     */
    public function getEstatusCredito()
    {
        return $this->container['estatus_credito'];
    }

    /**
     * Sets estatus_credito
     *
     * @param string $estatus_credito estatus_credito
     *
     * @return $this
     */
    public function setEstatusCredito($estatus_credito)
    {
        $this->container['estatus_credito'] = $estatus_credito;

        return $this;
    }

    /**
     * Gets desc_tipo_contrato
     *
     * @return \Swagger\Client\Model\CatalogoTipoContrato
     */
    public function getDescTipoContrato()
    {
        return $this->container['desc_tipo_contrato'];
    }

    /**
     * Sets desc_tipo_contrato
     *
     * @param \Swagger\Client\Model\CatalogoTipoContrato $desc_tipo_contrato desc_tipo_contrato
     *
     * @return $this
     */
    public function setDescTipoContrato($desc_tipo_contrato)
    {
        $this->container['desc_tipo_contrato'] = $desc_tipo_contrato;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
